name: System
version: ${project.version}
main: de.paintabletoast.system.boot.Core
api-version: 1.16
authors: [ PaintableToast ]
description: A Plugin
website: paintabletoast.de
commands:
  paintabletoast:
